### PR TITLE
Check for native support and only enhance where necessary

### PR DESCRIPTION
**Pull request by ryanmitchell**
Great work with this polyfill.

Here's a suggested enhancement which allows it to be used as a fallback - only affect fields that aren't natively supported by the browser.

### CODE REVIEW

**Comment by dperini** [comment]
Thank you Ryan for the contribution, unfortunately I am short on time currently to review and apply but I will do it asap.

If i remember well enough I am already doing some check to avoid overwriting browser functionalities.

One quick question: why removing the 'data-regex' attributes ? No browser that I know implements that so it's not going to overwrite anything functional.
Or am I missing something ?

**Comment by ryanmitchell** [comment]
To be honest I just applied the check on everything - assuming the data-regex were part of the fallback. I guess I was trying to keep browsers with support totally clean.

I couldn't see any functionality check in place - so if there is could you let me know where so I can test to see if its working for me?

**Comment by dperini** [comment]
Ryan,
could you show a small example of "nwxform" overwriting browser native functionalities ?
This would help me avoid many tests and see the problem instead of hunting it.

**Comment by ryanmitchell** [comment]
Hello. Sorry for the delay - I've only just now been able to come back to the code.

All I was trying to do was ensure that the 'upgrade' to the validation was only applied where required. As it stood the data-regex was always being applied even if there was browser support for the types of color, number etc - and in this case I feel the browser's native validation on input should be used.

What do you think?

**Comment by dperini** [comment]
@ryanmitchell 
as explained above the "data-regex" attribute is not part of any standard or native interface.

If you don't want that special functionality it offers just don't put that attribute on your elements.

You are probably confusing the functionality of "data-regex" with the functionality of the HTML5 "pattern" attribute, which is a native thing in browsers supporting it and that also accepts a regular-expression as it's value.

However the scope of the "data-regex" attribute is different. It allows a regex check for every keystroke the user types so for example you can block non numeric keystroke in INPUT elements.

There is also the possibility that I don't exactly understand what you mean, therefore I  suggested above to send me a simple HTML example showing were "nwxforms" fails or overwrites some native functionality.

**Comment by ryanmitchell** [comment]
Maybe I'm not explaining very well.

The data-regex is being added to input type=color, input type=number, even when the browser supports the input type natively.

Thats why I added the check for native support.

**Comment by dperini** [comment]
@ryanmitchell,
what you described above is exactly the expected behavior, the "data-regex" attribute is added because there is no support for it in any browsers, even the newest browsers don't support the functionality offered by the "data-regex" attribute. This means you cannot test support for that functionality.

However while reviewing your issue I found a bug that my have affected your testing.

The bug is on line 479, I forgot a backslash in the regular expression for type 'color':

    element.setAttribute('data-regexp', '[-\w#]');
should be:

    element.setAttribute('data-regexp', '[-\\w#]');
I will fix this bug and setup a demo for you to look at with an `ìnput` of type number to better explain what the scope of the "data-regex" attribute.

**Comment by dperini** [comment]
Fixed the missing backslash in the "data-regex" attribute value for `color` input types.

**Pull request closed without merging**
